name: evently_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  animated_toggle_switch: ^0.8.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  flutter_launcher_icons: ^0.14.4
  icons_plus: ^5.0.0
  shared_preferences: ^2.5.3
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/images_app/icon_app/icon_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/images_app/
    - assets/images/images_app/icon_app/
